export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERRORS = 'GET_USER_ERRORS';

export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS';
export const NEW_USER_LOADING = 'NEW_USER_LOADING';

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';